[project]
name = "all-models-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.129.0",
    "openai>=2.21.0",
    "transformers>=5.2.0",
    "uvicorn>=0.41.0",
]
